AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an analytics agent role to allow cross account data transfert in to the datalake

Resources:

  AgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "Project-Agent-Role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole' # TODO this is a todo comment
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

Outputs:

  AgentRoleArn:
    Description: The Analytics Agent Role ARN
    Value: !GetAtt AgentRole.Arn
